### ISSUE TITLE
question - ssh passwords from rackspace cloud servers

### ISSUE THREAD

**Issue by Marak** [nodejitsu/node-cloudservers#1]
do we get the ssh password for a spawned server?

do we get to assign the password for a new server?

thanks!

**Comment by indexzero** [comment]
Right now, we are getting 500 service unavailable responses from Rackspace on any POST, PUT, & DELETE request. 

The API method is CloudServer.update
http://github.com/nodejitsu/node-cloudservers/blob/master/lib/cloudservers/cloud-server.js#L151

**Comment by Marak** [comment]
i wasn't asking about the actual state of where we are what, but how its SUPPOSE to work.

**Comment by indexzero** [comment]
<pre>

var cloudservers = require('cloudservers'),
    sys = require('sys');

cloudservers.setAuth(cloudservers.config.auth, function () {
  cloudservers.getServer(123456, function (err, server) {
    server.update('server-username', 'server-password', function () {
      sys.puts('server now updated with new username and password');
    })
  });
});
</pre>
