### ISSUE TITLE
Please push latest to npm (auth URL issue)

### ISSUE THREAD

**Issue by focusaurus** [nodejitsu/node-cloudservers#16]
It seems there is no version yet in the NPM registry that contains this fix: 7683bcd07329fd3c85ecd77666e0e562c9970d9d

Can we get a 0.2.9 or 0.2.10 into npm for this fix, please?

**Comment by mmalecki** [comment]
@bmeck Assigned to you, please push it.

**Comment by indexzero** [comment]
Done

**Comment by focusaurus** [comment]
Thanks! :-)
