### ISSUE TITLE
Error: Failed to parse json, when installing cloudservers

### ISSUE THREAD

**Issue by abhinavxrai** [nodejitsu/node-cloudservers#2]
After install node.js, I attempted to install cloudservers as per your instructions. I get an error printed below. It seems to be invalid json error.

~/node# npm install cloudservers
npm info it worked if it ends with ok
npm info using npm@0.3.2
npm info using node@v0.5.0-pre
npm info fetch http://registry.npmjs.org/cloudservers/-/cloudservers-0.2.0.tgz
npm info calculating sha1 /tmp/npm-1298154452380/1298154452380-0.9361977083608508/tmp.tgz
npm info shasum 12556ab1cb37d1becac19a3ef5360b5cbbecd668
npm ERR! couldn't read package.json in /tmp/npm-1298154452380/1298154452380-0.9361977083608508/contents/package
npm ERR! Error installing cloudservers@0.2.0
npm ERR! Error: Failed to parse json
npm ERR! Unexpected token ]
npm ERR! {
npm ERR!   "name": "cloudservers",
npm ERR!   "description": "A client implementation for Rackspace CloudServers in node.js",
npm ERR!   "version": "0.2.0",
npm ERR!   "author": "Charlie Robbins charlie.robbins@gmail.com",
npm ERR!   "contributors": [
npm ERR!     { "name": "Elijah Insua", "email": "tmpvar@gmail.com" },
npm ERR!     { "name": "Matthew Bergman", "email": "mzbphoto@gmail.com" }, 
npm ERR!   ],
npm ERR!   "repository": {
npm ERR!       "type": "git",
npm ERR!       "url": "http://github.com/nodejitsu/node-cloudservers.git" 
npm ERR!   },
npm ERR!   "keywords": ["cloud computing", "api", "rackspace cloud", "cloudservers"],
npm ERR!   "dependencies": {
npm ERR!     "request": ">= 0.10.0",
npm ERR!     "vows": ">= 0.5.2"
npm ERR!   },
npm ERR!   "main": "./lib/cloudservers",
npm ERR!   "scripts": { "test": "vows test/_-test.js --spec" },
npm ERR!   "engines": { "node": ">= 0.3.0" }
npm ERR! }
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.2/package/lib/utils/read-json.js:73:13
npm ERR!     at P (/usr/local/lib/node/.npm/npm/0.3.2/package/lib/utils/read-json.js:62:40)
npm ERR!     at cb (/usr/local/lib/node/.npm/npm/0.3.2/package/lib/utils/graceful-fs.js:31:9)
npm ERR!     at [object Object].<anonymous> (fs.js:86:5)
npm ERR!     at [object Object].emit (events.js:39:17)
npm ERR!     at afterRead (fs.js:843:12)
npm ERR! Report this *entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm not ok

**Comment by Marak** [comment]
There's an erroneous comma here: https://github.com/nodejitsu/node-cloudservers/blob/master/package.json#L8

I'm surprised this hasn't come up before, it could be NPM is getting stricter about parsing package.json. I'm assuming removing this comma will fix the issue.

**Comment by abhinavxrai** [comment]
You're correct, I'm surprised I failed to notice that.
Anyone has access to commit to this repository to make this change?

**Comment by Marak** [comment]
I've got commit access, but since the package is published to NPM under indexzero's name, I think we need to wait for him to push to NPM. Should be fixed within a day, sorry for the inconvenience. 

As a stop gap, you could clone the repo, adjust the one line, and run "npm link ." from inside the repo.

**Comment by indexzero** [comment]
Will get to this tonight. Sorry for the confusion. This seems to be an issue across a couple of our projects.

**Comment by indexzero** [comment]
Fixed in 0.2.1. afe590dbdd48ed366fb365d515d11e5857ee97ba

**Comment by abhinavxrai** [comment]
thanks for the quick response and solution indexzero.
