### ISSUE TITLE
node v0.5.0-pre

### ISSUE THREAD

**Issue by bryfry** [nodejitsu/node-cloudservers#5]
npm ERR! Not compatible with your version of node/npm: cloudservers@0.2.4
npm ERR! Required: {"node":"0.4.x"}
npm ERR! Actual:   {"npm":"1.0.6","node":"v0.5.0-pre"}

**Comment by lukeholder** [comment]
i get the same

**Comment by indexzero** [comment]
Updated the package.json and pushed out 0.2.5. Use node 0.5.0-pre at your peril: you should really run against v0.4.8:

```
cd /path/to/your/node/installation
[sudo] make distclean
[sudo] git pull && git checkout v0.4.8
[sudo] ./configure
[sudo] make && make install
```
