### ISSUE TITLE
Possible to install node-cloudservers with cloud9ide?

### ISSUE THREAD

**Issue by edtalmadge** [nodejitsu/node-cloudservers#7]
I'm having numerous issues trying to setup a node.js development environment on Windows/Cygwin.

Instead of using Windows, is it a good idea to just use Cloud9ide? (http://www.cloud9ide.com)

They allow you to use npm right out of the box. So, I could just npm install cloudservers.... and continue from that point without the Windows setup headache.

If that works, I think it could really simplify the node hosting setup process for command line/node beginners like myself. Been trying for 2 months to get a good setup.

**Comment by indexzero** [comment]
I've heard good things about running a Linux VirtualBox on Windows workstations. That's what @bmeck at Nodejitsu does. Maybe if I summon him to this thread he will be able to give you a couple pointers.

**Comment by bmeck** [comment]
Well, node-cloudservers should be able to _run_ on Cygwin, but I would
discourage it. Cygwin is glitchy at times (its not a 100% port) and
exceedingly hard to patch. I avoid it like plague except when doing
shell scripting on Windows (why is Powershell so hard to use...). Back
to topic though:

Yep, I use VirtualBox with Ubuntu 11.4 . It makes some things nice and
convenient as you can do machine backups easily.
The one oddity is on older Ubuntus and Nodes the http web requests
node handles/sends can be glitchy and not be sent/recieved.

As for Cloud9ide, personally I love it, but I don't have full access
to somethings easily like SSH-keys, a C++ compiler, and I can't do
local dev if I don't have internet on the same setup.

Overall I'd stick to a VM w/ Linux if you want the best experience on
Windows. Maybe someday it will be easier to have Node on windows.

**Comment by edtalmadge** [comment]
Great advice! I'll give VirtualBox a try.

**Comment by indexzero** [comment]
@bmeck Thanks for the thoughtful reply. I'm going to close this issue unless you have any objections edtalmadge

**Comment by edtalmadge** [comment]
Thanks again and please close the issue.
